"""MLB schema contracts for historical and runtime feature sets."""

from __future__ import annotations


MLB_REQUIRED_FEATURES = [
    "elo_diff",
    "rest_diff",
    "travel_distance",
    "travel_fatigue_diff",
    "injury_impact_diff",
    "pitcher_diff",
    "starter_rating_diff",
    "bullpen_rating_diff",
    "hitting_rating_diff",
    "home_split_diff",
    "recent_form_diff",
    "home_moneyline",
    "spread",
    "implied_home_prob",
    "spread_abs",
    "is_favorite",
]

MLB_HISTORICAL_COLUMNS = [
    "date",
    "game_id",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "home_win",
    "home_cover",
    "over_hit",
    "closing_moneyline_home",
    "closing_moneyline_away",
    "closing_spread_home",
    "closing_total",
    "elo_home",
    "elo_away",
    "elo_diff",
    "rest_days_home",
    "rest_days_away",
    "rest_diff",
    "travel_distance_home",
    "travel_distance_away",
    "travel_distance",
    "travel_fatigue_diff",
    "injury_impact_home",
    "injury_impact_away",
    "injury_impact_diff",
    "pitcher_era_home",
    "pitcher_era_away",
    "pitcher_diff",
    "starter_rating_home",
    "starter_rating_away",
    "starter_rating_diff",
    "bullpen_rating_home",
    "bullpen_rating_away",
    "bullpen_rating_diff",
    "hitting_rating_home",
    "hitting_rating_away",
    "hitting_rating_diff",
    "home_split_home",
    "home_split_away",
    "home_split_diff",
    "recent_form_home",
    "recent_form_away",
    "recent_form_diff",
    "home_moneyline",
    "spread",
    "implied_home_prob",
    "spread_abs",
    "is_favorite",
]
